# prometheus k14s objects managed by extension manager
# kubectl create secret docker-registry harbor-registry-secret -n nginx --docker-server=<docker-ip-or-url>  --docker-username=<docker-user> --docker-password=<docker-secret>
---
apiVersion: clusters.tmc.cloud.vmware.com/v1alpha1
kind: Extension
metadata:
  name: prometheus
  namespace: tanzu-system-monitoring
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  description: prometheus
  version: "v2.17.1_vmware.1"
  name: prometheus
  namespace: tanzu-system-monitoring
  deploymentStrategy:
    type: KUBERNETES_NATIVE
  objects: |
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: prometheus
      annotations:
        tmc.cloud.vmware.com/orphan-resource: "true"
    spec:
      syncPeriod: 5m
      serviceAccountName: prometheus-extension-sa
      fetch:
        - image:
            #url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.0_vmware.1
            url: myminseok/tkg-extensions-templates:v1.3.0_vmware.1
            ## to use private docker repo, use generic secret. (kapp 0.19.0+ supports docker secret)
            ## https://carvel.dev/kapp-controller/docs/latest/config/#image-authentication
            secretRef:
              ## kubectl create secret generic docker-registry-secret-generic --from-literal=username=dockeraccountname --from-literal=password=XXXXXX -n tanzu-system-monitoring
              name: docker-registry-secret-generic
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
              - tkg-extensions/common
              - tkg-extensions/monitoring/prometheus
            inline:
              pathsFrom:
                - secretRef:
                    name: prometheus-data-values
              paths:
                add-imagepullsecrets.yml: |
                  #@ load("@ytt:overlay", "overlay")
                  #@overlay/match by=overlay.subset({"kind": "ServiceAccount"}), expects="0+"
                  ---
                  #@overlay/match missing_ok=True
                  imagePullSecrets:
                  - name: harbor-registry-secret
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]
