apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
   app: redis-server
spec:
  storageClassName: pacific-gold-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
