#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"KubeadmConfig"})
---
spec:
  #@overlay/match missing_ok=True
  files:
    #@overlay/remove
    #@overlay/match by="path", expects="0+"
    - path: /etc/ssl/certs/tkg-custom-ca.pem
    #@overlay/append
    - content: #@ data.read("tkg-custom-ca.pem")
      owner: root:root
      permissions: "0644"
      path: /etc/ssl/certs/tkg-custom-ca.pem
  #@overlay/match missing_ok=True
  preKubeadmCommands:
    #@overlay/match by=overlay.subset('! which rehash_ca_certificates.sh 2>/dev/null || rehash_ca_certificates.sh'), expects="0+"
    #@overlay/remove
    -

    #@overlay/match by=overlay.subset('! which update-ca-certificates 2>/dev/null || (mv /etc/ssl/certs/tkg-custom-ca.pem /usr/local/share/ca-certificates/tkg-custom-ca.crt && update-ca-certificates)'), expects="0+"
    #@overlay/remove
    -
    #! For Photon OS
    #@overlay/append
    - '! which rehash_ca_certificates.sh 2>/dev/null || rehash_ca_certificates.sh'
    #! For Ubuntu
    #@overlay/append
    - '! which update-ca-certificates 2>/dev/null || (mv /etc/ssl/certs/tkg-custom-ca.pem /usr/local/share/ca-certificates/tkg-custom-ca.crt && update-ca-certificates)'
